name: Minify Assets

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g clean-css-cli
          npm install -g terser
          
      - name: Minify CSS and add hash
        run: |
          # First minify the CSS
          cleancss -o styles.min.css styles.css
          # Then calculate hash and rename
          HASH=$(sha256sum styles.min.css | cut -c1-8)
          mv styles.min.css "styles.min.${HASH}.css"
          
      - name: Minify JavaScript and add hash
        run: |
          # First minify the JavaScript files
          terser script.js -o script.min.js
          terser icons.js -o icons.min.js
          # Then calculate hashes and rename
          HASH_SCRIPT=$(sha256sum script.min.js | cut -c1-8)
          HASH_ICONS=$(sha256sum icons.min.js | cut -c1-8)
          mv script.min.js "script.min.${HASH_SCRIPT}.js"
          mv icons.min.js "icons.min.${HASH_ICONS}.js"
          
      - name: Update HTML with new asset names
        run: |
          # Create a temporary file to store the new HTML
          cp index.html index.temp.html
          # Replace asset references with hashed versions
          for file in *.min.*.css *.min.*.js; do
            if [ -f "$file" ]; then
              base=$(echo $file | cut -d. -f1)
              ext=$(echo $file | cut -d. -f3)
              sed -i "s/${base}.min.${ext}/${file}/g" index.temp.html
            fi
          done
          # Copy the updated HTML back
          mv index.temp.html index.html
          
      - name: Commit and push minified files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.min.*
          git commit -m "Minify assets with content hashing" -a || echo "No changes to commit"
          git push 